version: '2'
services:
  web:
    restart: always
    build: .
    container_name: meanjs
    ports:
     - "3000:3000"
     - "5858:5858"
     - "8080:8080"
     - "35729:35729"
    environment:
     - NODE_ENV=development
     - DB_1_PORT_27017_TCP_ADDR=db
    depends_on:
     - mongo
     - couch
    volumes_from:
     - web-data
  web-data:
    build: .
    entrypoint: /bin/true
    volumes:
     - ./:/opt/mean.js
     - /opt/mean.js/node_modules
     - /opt/mean.js/public
     - /opt/mean.js/uploads
  mongo:
    image: mongo:3.2
    restart: always
    ports:
     - "27017:27017"
    volumes_from:
      - mongo-data
  mongo-data:
    image: mongo:3.2
    volumes:
      - /data/db
      - /var/lib/mongodb
      - /var/log/mongodb
    entrypoint: /bin/true
  couch:
    image: klaemo/couchdb
    restart: always
    ports:
    - "5984:5984"
    volumes_from:
      - couch-data
  couch-data:
    image: klaemo/couchdb
    volumes:
      - /data/db
      - /var/lib/couchdb
      - /var/log/couchdb
    entrypoint: /bin/true
