web:
  build: .
  links:
    - db
    - couch
  ports:
    - "3000:3000"
  environment:
    NODE_ENV: production
db:
  image: mongo
  ports:
    - "27017:27017"
couch:
  image: klaemo/couchdb
  ports:
    - "5984:5984"