
name: PR Jira integration

on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  pr_jira_validate:
    runs-on: ubuntu-latest
    name: A job for pr jira integration
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Dump env
        run: env
      - name: post token
        run:  |
          OIDC_TOKEN=$(curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=o6s" -H "User-Agent: actions/oidc-client" -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN")
        id: get-token
      - name: saveToken
        run: echo '::set-output name=oidc-token::"$OIDC_TOKEN"'
      - name: print token
        run: echo "The token is ${{ steps.saveToken.outputs.oidc-token }}"
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          role-to-assume: arn:aws:iam::448470023870:role/GithubS3ReadRole
          aws-region: us-east-1
      - name: access S3
        run: aws s3 ls s3://bountifulkids.profile.pics/06fcbb93798179d563af98dd2abca712
      - name: pr jira
        uses: kjorgens/pr-jira-action@7c314ddffed0ac0e25af2fcf8fe14a97d16be9a8 # Uses an action in the root directory
        id: prJira
      - name: do nothing
        run: echo "The time was not set"
