
name: PR Jira integration

on: [pull_request]

permissions:
  id-token: write
  contents: read

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job for pr jira integration
    steps:
      # To use this repository's private action, you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@b8c74de753fbcb4868bf2011fb2e15826ce973af
        with:
          role-to-assume: arn:aws:iam::448470023870:role/ExampleGithubRole
          aws-region: us-east-1
      - name: pr jira
        uses: kjorgens/pr-jira-action@main # Uses an action in the root directory
        id: prJira
